//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderGarten.Model.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Children
    {
        public int ID { get; set; }
        public Nullable<int> FatherId { get; set; }
        public string Father
        {
            get
            {
                using (var context = new KinderGartenDbEntities())
                {
                    var a = context.Parents.Where(x => x.ID == FatherId)?.FirstOrDefault();
                    return a.Surname + " " + a.Name;
                }
            }
        }
        public string GroupName
        {
            get
            {
                using (var context = new KinderGartenDbEntities())
                {
                    var a = context.Groups.Where(x => x.ID == GroupID)?.FirstOrDefault();
                    return a.Name;
                }
            }
        }
        public string Mother
        {
            get
            {
                using (var context = new KinderGartenDbEntities())
                {
                    var a = context.Parents.Where(x => x.ID == MomId)?.FirstOrDefault();
                    return a.Surname + " " + a.Name;
                }
            }
        }
        public Nullable<int> MomId { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }

        public virtual Groups Groups { get; set; }
        public virtual Parents Parents { get; set; }
        public virtual Parents Parents1 { get; set; }
    }
}
