//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderGarten.Model.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Children = new HashSet<Children>();
        }
    
        public int ID { get; set; }
        public string Teacher1
        {
            get
            {
                using (var context = new KinderGartenDbEntities())
                {
                    var a = context.Teachers.Where(x => x.ID == Teachers1Id)?.FirstOrDefault();
                    return a.Surname + " " + a.Name;
                }
            }
        }
        public string Teacher2
        {
            get
            {
                using (var context = new KinderGartenDbEntities())
                {
                    var a = context.Teachers.Where(x => x.ID == Teachers2Id)?.FirstOrDefault();
                    return a.Surname + " " + a.Name;
                }
            }
        }
        public Nullable<int> Teachers1Id { get; set; }
        public Nullable<int> Teachers2Id { get; set; }
        public string Name { get; set; }
        public int AgeFrom { get; set; }
        public int AgeTo { get; set; }
        public int MaxCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Children> Children { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Teachers Teachers1 { get; set; }
    }
}
